namespace DrugSchedule.Client.Networking;

internal static class EndpointsPaths
{
    public const string Auth_Login = "Auth/Login";
    public const string Auth_Register = "Auth/Register";
    public const string Auth_RefreshToken = "Auth/RefreshToken";
    public const string Auth_UsernameAvailable = "Auth/UsernameAvailable";
    public const string Auth_RevokeTokens = "Auth/RevokeTokens";
    public const string Contacts_GetAll = "Contacts/GetAll";
    public const string Contacts_GetCommon = "Contacts/GetCommon";
    public const string Contacts_GetSingleExtended = "Contacts/GetSingleExtended";
    public const string Contacts_GetManyExtended = "Contacts/GetManyExtended";
    public const string Contacts_AddOrUpdate = "Contacts/AddOrUpdate";
    public const string Contacts_Remove = "Contacts/Remove";
    public const string DrugLibrary_GetMedicament = "DrugLibrary/GetMedicament";
    public const string DrugLibrary_GetMedicamentExtended = "DrugLibrary/GetMedicamentExtended";
    public const string DrugLibrary_GetMedicaments = "DrugLibrary/GetMedicaments";
    public const string DrugLibrary_GetMedicamentsExtended = "DrugLibrary/GetMedicamentsExtended";
    public const string DrugLibrary_GetManufacturer = "DrugLibrary/GetManufacturer";
    public const string DrugLibrary_GetManufacturers = "DrugLibrary/GetManufacturers";
    public const string DrugLibrary_GetReleaseForms = "DrugLibrary/GetReleaseForms";
    public const string Schedule_SearchForSchedule = "Schedules/SearchForSchedule";
    public const string Schedule_GetScheduleSimple = "Schedules/GetScheduleSimple";
    public const string Schedule_GetSchedulesSimple = "Schedules/GetSchedulesSimple";
    public const string Schedule_GetScheduleExtended = "Schedules/GetScheduleExtended";
    public const string Schedule_GetSchedulesExtended = "Schedules/GetSchedulesExtended";
    public const string Schedule_GetTakingConfirmations = "Schedules/GetTakingConfirmations";
    public const string Schedule_CreateSchedule = "Schedules/CreateSchedule";
    public const string Schedule_UpdateSchedule = "Schedules/UpdateSchedule";
    public const string Schedule_RemoveSchedule = "Schedules/RemoveSchedule";
    public const string Schedule_CreateRepeat = "Schedules/CreateRepeat";
    public const string Schedule_UpdateRepeat = "Schedules/UpdateRepeat";
    public const string Schedule_RemoveRepeat = "Schedules/RemoveRepeat";
    public const string Schedule_AddOrUpdateShare = "Schedules/AddOrUpdateShare";
    public const string Schedule_RemoveShare = "Schedules/RemoveShare";
    public const string Schedule_CreateConfirmation = "Schedules/CreateConfirmation";
    public const string Schedule_UpdateConfirmation = "Schedules/UpdateConfirmation";
    public const string Schedule_RemoveConfirmation = "Schedules/RemoveConfirmation";
    public const string Schedule_AddConfirmationImage = "Schedules/AddConfirmationImage";
    public const string Schedule_RemoveConfirmationImage = "Schedules/RemoveConfirmationImage";
    public const string User_GetMe = "User/GetMe";
    public const string User_Search = "User/Search";
    public const string User_UpdateProfile = "User/UpdateProfile";
    public const string User_ChangePassword = "User/ChangePassword";
    public const string User_SetAvatar = "User/SetAvatar";
    public const string User_RemoveAvatar = "User/RemoveAvatar";
    public const string UserDrugs_GetSingle = "UserDrugs/GetSingle";
    public const string UserDrugs_GetSingleExtended = "UserDrugs/GetSingleExtended";
    public const string UserDrugs_GetMany = "UserDrugs/GetMany";
    public const string UserDrugs_GetManyExtended = "UserDrugs/GetManyExtended";
    public const string UserDrugs_GetSharedExtended = "UserDrugs/GetSharedExtended";
    public const string UserDrugs_Add = "UserDrugs/Add";
    public const string UserDrugs_AddImage = "UserDrugs/AddImage";
    public const string UserDrugs_RemoveImage = "UserDrugs/RemoveImage";
    public const string UserDrugs_Update = "UserDrugs/Update";
    public const string UserDrugs_Remove = "UserDrugs/Remove";
}